Repository GSG-CF05/World-of-food-app--team9, pull requests merged in 2022-03, with the labels that each got.

#2 Create file structure
  details/details.css
  details/details.html
  index.html
  js/app.js
  landingPage/style.css
  menu/menu.css
  menu/menu.html
  wishlist/wishlist.css
  wishlist/wishlist.html
Labels: approved

#8 add assets folder to structure related to #7
  assets/logo.png
Labels: Awaiting review

#6 create readme file relate #4
  README.md
Labels: awaiting-review

#18 add product details html and css code
  details/assets/logo.png
  details/details.css
  details/details.html
Labels: approved

#20 crate menu page using css
  menu/menu.css
Labels: Awaiting review

#19 create menu page using html
  menu/menu.html
Labels: Awaiting review

#24 create json file
  food.json
Labels: approved

#28 move food.json file from / to assets folder related #27
  assets/food.json
Labels: approved

#30 modify menu page in html and replac the static data with api data
  menu/menu.html
Labels: request-change

#31 Restyling the modified elements in html
  menu/menu.css
Labels: Awaiting review

#34 change src script in html menu page
  menu/menu.html
Labels: Awaiting review

#32 create menu page with javascript
  js/menu.js
Labels: Awaiting review

#36 29 make meals pagination menu page
  js/menu.js
  menu/menu.css
  menu/menu.html
Labels: Awaiting review

#37 add whole js code and comment changes for other codes
  details/details.css
  details/details.html
  details/details.js
Labels: approved

#38 adding items to the local Storge and make the wish list functionality
  js/menu.js
  menu/menu.css
Labels: approve

#39 create js file for wish list page and adding (css ,js) code
  js/wishlist.js
  wishlist/wishlist.css
  wishlist/wishlist.html
Labels: awaiting-review

#41 complete write READMR file
  README.md
  assets/wireframe.png
  index.html
Labels: Awaiting review
